### ISSUE TITLE
Add some block previews

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-bootstrap3#19]
Based on https://github.com/luyadev/luya-module-cms/pull/148

**Comment by nadar** [comment]
Which blocks do you think need a preview? I don't think it makes sense for every block, but in general: yes 👍

**Comment by boehsermoe** [comment]
Maybe the LayoutBlock and MapBlock?

**Comment by nadar** [comment]
what kind of picture would you show for layout block?
