### ISSUE TITLE
Add i18n to default map

### ISSUE THREAD

**Issue by nick-denry** [luyadev/luya-bootstrap3#7]
Hi!

I guess it is good to use another languages instead of fixed 'de' for the default map.

I'm not definitely sure if composition language is ok for the block view.

Made PR for this: https://github.com/luyadev/luya-bootstrap3/pull/6

**Comment by nadar** [comment]
As already mentioned in the PR #6 , i think you can close this issue in favor of the PR - i also added the issue text into the pr description. In future, you can only do a PR if you like, and add the description there would be enough for us. As you wish.

Thanks anyhow!

**Comment by nick-denry** [comment]
Closed due to PR https://github.com/luyadev/luya-bootstrap3/pull/6
